### ISSUE TITLE
Doesn't work git neither over HTTP or over SSH

### ISSUE THREAD

**Issue by xaionaro** [raphendyr/gitlabhq#11]
Over SSH:
works clone
doesn't work push

Over HTTP:
doesn't work clone and push

$ git push -u origin master
error: src refspec master does not match any.
error: failed to push some refs to 'gitlab@gitlab.ut.mephi.ru:xaionaro/test.git'

$ git clone https://gitlab.ut.mephi.ru/xaionaro/private.git
Cloning into 'private'...
Username for 'https://gitlab.ut.mephi.ru': xaionaro
Password for 'https://xaionaro@gitlab.ut.mephi.ru': 
fatal: Authentication failed

**Comment by xaionaro** [comment]
Seems, that I got it work over HTTP. It's need to set password via Web-interface and use this password for clone/push.

**Comment by raphendyr** [comment]
I didn't validate https pam authentication. I did try to handle that, but as usual, didn't validate. SSH should work fine. Pam has nothing to do with that side. At least in our environment it works well.

I try to make https push/pull/auth work with 6.4 as eclipse users might need it.

**Comment by xaionaro** [comment]
I solved the problem with HTTP(s). I've modified my gitlab instance to save correct password hashes to DB while creating an user authenticated by PAM or LDAP.

Also I've solved problem with SSH. It was due to SSH connection multiplexing. It can be disabled on server side with:

```
Match User gitlab
        MaxSessions 1
```

in /etc/ssh/sshd_config.

**Comment by raphendyr** [comment]
Hmm.. I have to investigate the ssh problem some day. And I need to fix the password thing. The hole point is not to need gitlab passwords.

Thanks for the information :)

**Comment by xaionaro** [comment]
> And I need to fix the password thing.

I can prepare a patch how I solved that issue. But I'm not a ruby programmer, so… :)

> The hole point is not to need gitlab passwords.

What do you mean?

**Comment by raphendyr** [comment]
Any kind of patch is ok. I'm not ruby coder either, but I'm getting better ;)

Point about passwords, were that when using pam or ldap, there shouldn't be any need for gitlab internal password as pam/ldap back end would authenticate user in all cases..

**Comment by raphendyr** [comment]
HTTPS is fixed in 6-4-pam, well at least worked in my tests.

fixing commit: raphendyr/gitlabhq@c08c34c
