### ISSUE TITLE
Broken link in doc/install/installation.md

### ISSUE THREAD

**Issue by xaionaro** [raphendyr/gitlabhq#9]
There's a broken link to "https://raw.github.com/gitlabhq/gitlab-recipes/master/init.d/gitlab" in doc/install/installation.md

---
## Install Init Script

Download the init script (will be /etc/init.d/gitlab):

```
sudo curl --output /etc/init.d/gitlab https://raw.github.com/gitlabhq/gitlab-recipes/master/init.d/gitlab
sudo chmod +x /etc/init.d/gitlab
```

**Comment by xaionaro** [comment]
The same problem in branch "6-3-pam"

**Comment by raphendyr** [comment]
Please read the doc's from upstream source. I haven't even thought about it. Also `master` branch is not updated. 

List of branches should show you the newest ones: https://github.com/raphendyr/gitlabhq/branches
